HOME_LOCATION = "/home/pi/NEMSELFIE/nemselfie-python/"
PICTURES_LOCATION = HOME_LOCATION + "EventPictures/"
SCREEN_X = 800
SCREEN_Y = 480

PICTURE_WIDTH = 800
PICTURE_HEIGHT = 480

IDDLE_BRIGHTNESS = 35
PICTURE_BRIGHTNESS = 50
FLASH_BRIGHTNESS = 100
FLASH_DURATION = 200 #FLASH DURATION IN MILLISECONDS

IDDLE_TEXT = "Tryk her for at tage et NemSelfie!"
PICTURE_TEXT_BEFORE = "Er du klar?"
PICTURE_TEXT_1 = "3..."
PICTURE_TEXT_2 = "2..."
PICTURE_TEXT_3 = "1..."
PICTURE_TEXT_AFTER = "Tak! :-)"

NEW_PICTURE_TEXT = "Tag nyt billede"
KEEP_PICTURE_TEXT = "Gem billede"
