IDDLE_BRIGHTNESS = 40
PICTURE_BRIGHTNESS = 50
FLASH_BRIGHTNESS = 100

IDDLE_TEXT = "Tryk her for at tage et NemSelfie!"
PICTURE_TEXT_BEFORE = "Er du klar?"
PICTURE_TEXT_1 = "3..."
PICTURE_TEXT_2 = "2..."
PICTURE_TEXT_3 = "1..."
PICTURE_TEXT_AFTER = "Tak! :-)"
